version: "3.8"

services:
  app:
    build: .
    container_name: doo-store
    restart: unless-stopped
    # privileged: true
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
      ENV: "prod"
      STORAGE: sqlite
      SQLITE_PATH: "./db/app.db"
      DATA_DIR: "/Users/mac-47/Desktop/zeniein/devlop/doo-store/docker/dood"
    volumes:
      - ./docker/sqlite:/app/db
      - ./docker/dood:/Users/mac-47/Desktop/zeniein/devlop/doo-store/docker/dood
      - /var/run/docker.sock:/var/run/docker.sock