definitions:
  dto.Response:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      msg:
        example: success
        type: string
    type: object
  request.AppInstall:
    properties:
      name:
        type: string
      params:
        additionalProperties: true
        type: object
    type: object
  request.AppInstalledOperate:
    properties:
      action:
        type: string
      params:
        additionalProperties: true
        type: object
    type: object
  request.AppUnInstall:
    type: object
info:
  contact:
    email: xxyijixx@gmail.com
    name: xxyijixx
  description: Description of Doo Store API documentation
  license:
    name: AGPL-3.0
    url: https://opensource.org/license/agpl-v3
  title: Doo Store API Documentation
  version: "1.0"
paths:
  /apps:
    get:
      parameters:
      - default: 1
        description: page
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: page_size
        in: query
        name: page_size
        required: true
        type: integer
      - description: class
        in: query
        name: class
        type: string
      - description: name
        in: query
        name: name
        type: string
      - description: id
        in: query
        name: id
        type: integer
      - description: description
        in: query
        name: description
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: app page
      tags:
      - app
  /apps/{key}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      - description: RequestBody
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AppUnInstall'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: app uninstall
      tags:
      - app
    post:
      consumes:
      - application/json
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      - description: RequestBody
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AppInstall'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: app install
      tags:
      - app
    put:
      consumes:
      - application/json
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      - description: RequestBody
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AppInstalledOperate'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: app update
      tags:
      - app
  /apps/{key}/detail:
    get:
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: app detail
      tags:
      - app
  /apps/installed:
    get:
      parameters:
      - default: 1
        description: page
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: page_size
        in: query
        name: page_size
        required: true
        type: integer
      - description: class
        in: query
        name: class
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: installed app page
      tags:
      - app
  /apps/tags:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: app tags
      tags:
      - app
  /public/health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: health
      tags:
      - public
securityDefinitions:
  BearerAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
